# author: serialt

- name: Copy script. 
  template:
    src: CentOS-7.repo.j2
    dest: /etc/yum.repos.d/CentOS-7.repo
    mode: 644
  register: copy_script
  when: ansible_distribution_major_version == '7'


- name: Change YUM for 7.
  shell: sed -e 's|^mirrorlist=|#mirrorlist=|g' \
         -e "s|^#baseurl=http://mirror.centos.org|baseurl={{ yum_source_url }}|g" \
         -i.bak \
         /etc/yum.repos.d/CentOS-7.repo
  when: ansible_distribution_major_version == '7'
  register: change_yum
- debug:
    var: change_yum

- name: Change all YUM for 7.
  shell: sed -e 's|^mirrorlist=|#mirrorlist=|g' \
         -e "s|^#baseurl=http://mirror.centos.org|baseurl={{ yum_source_url }}|g" \
         -i.bak \
         /etc/yum.repos.d/CentOS-*.repo
  when: ansible_distribution_major_version == '7' and change_all_yum
  register: change_yum
- debug:
    var: change_yum

- name: Change EPEL for 7.
  shell: sed -e 's!^metalink=!#metalink=!g' \
        -e 's!^#baseurl=!baseurl=!g' \
        -e 's@https\?://download.fedoraproject.org/pub@{{ yum_source_url }}@g' \
        -i /etc/yum.repos.d/epel.repo /etc/yum.repos.d/CentOS-7.repo
  register: change_epel
  when: ansible_distribution_major_version == '7'

- name: Import key from RLRepo
  shell: rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

- name: Install ELrepo 
  yum:
    name: https://www.elrepo.org/elrepo-release-{{ ansible_distribution_major_version }}.el{{ ansible_distribution_major_version }}.elrepo.noarch.rpm
    state: present
  when: elrepo_install

- name: Update yum cache.
  shell: "yum clean all && yum makecache"
  args:
    warn: no





